document.addEventListener('DOMContentLoaded', () => {
    // ----------------------------------------------------
    // 1. Theme Configuration (Dark/Light Mode Sync)
    // ----------------------------------------------------
    const themeCheckboxes = document.querySelectorAll('.theme-switch-input');
    
    // Check and set saved theme or default to system theme
    const savedTheme = localStorage.getItem('theme');
    const systemPrefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
    const isDark = savedTheme === 'dark' || (!savedTheme && systemPrefersDark);
    
    // Set theme class on <html> and sync all checkboxes
    if (isDark) {
        document.documentElement.classList.add('dark-theme');
    } else {
        document.documentElement.classList.remove('dark-theme');
    }
    
    themeCheckboxes.forEach(cb => {
        cb.checked = isDark;
        cb.addEventListener('change', () => {
            const newDarkState = cb.checked;
            // Sync all checkboxes on the page
            themeCheckboxes.forEach(other => {
                other.checked = newDarkState;
            });
            
            if (newDarkState) {
                document.documentElement.classList.add('dark-theme');
                localStorage.setItem('theme', 'dark');
            } else {
                document.documentElement.classList.remove('dark-theme');
                localStorage.setItem('theme', 'light');
            }
        });
    });

    // ----------------------------------------------------
    // 2. Fetch Interceptor to Resolve Relative Markdown Image Paths
    // ----------------------------------------------------
    let currentMarkdownBaseUrl = '';

    // Intercept window.fetch to capture raw markdown URL path
    const originalFetch = window.fetch;
    window.fetch = async function(...args) {
        const url = args[0];
        if (typeof url === 'string') {
            try {
                // Use window.location.href as the base URL to safely handle file:// and http:// protocols
                const urlObj = new URL(url, window.location.href);
                const pathname = urlObj.pathname;
                if (pathname.endsWith('.md')) {
                    // Extract directory base URL
                    const lastSlashIndex = urlObj.href.lastIndexOf('/');
                    if (lastSlashIndex !== -1) {
                        currentMarkdownBaseUrl = urlObj.href.substring(0, lastSlashIndex + 1);
                    }
                }
            } catch (e) {
                console.error("Failed to parse fetch URL:", e);
            }
        }
        return originalFetch.apply(this, args);
    };

    // ----------------------------------------------------
    // 3. Active Link State & Content Image URL Resolving
    // ----------------------------------------------------
    const tutorialList = document.getElementById('tutorial-list');
    const contentDisplay = document.getElementById('content-display');

    // MutationObserver to rewrite relative image paths when content is inserted
    const contentObserver = new MutationObserver((mutationsList) => {
        for (const mutation of mutationsList) {
            if (mutation.type === 'childList') {
                const imgs = contentDisplay.querySelectorAll('img');
                imgs.forEach(img => {
                    const src = img.getAttribute('src');
                    // Rewrite relative image paths using currentMarkdownBaseUrl
                    if (src && 
                        !src.startsWith('http://') && 
                        !src.startsWith('https://') && 
                        !src.startsWith('data:') && 
                        !src.startsWith('/') &&
                        currentMarkdownBaseUrl) {
                        img.src = currentMarkdownBaseUrl + src;
                    }
                });
            }
        }
    });

    if (contentDisplay) {
        contentObserver.observe(contentDisplay, { childList: true, subtree: true });
        
        // Add load class initially to show welcome content smoothly
        contentDisplay.classList.add('content-loaded-animation');
    }

    // ----------------------------------------------------
    // 4. Collapsible Category Directories with Chevrons
    // ----------------------------------------------------
    const listObserver = new MutationObserver(() => {
        // Find all strong elements (directory headers) generated by script.js
        const folderHeaders = tutorialList.querySelectorAll('strong:not(.processed)');
        folderHeaders.forEach(folder => {
            folder.classList.add('processed');
            
            // SVG chevron icon pointing down by default (folder open)
            const chevronSvg = `
                <svg class="chevron-icon" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                    <polyline points="6 9 12 15 18 9"></polyline>
                </svg>
            `;
            
            const folderNameText = folder.textContent;
            folder.innerHTML = chevronSvg + `<span>${folderNameText}</span>`;
            
            // Add click listener to toggle collapsed class on the parent list item (li)
            folder.addEventListener('click', (e) => {
                const parentLi = folder.closest('li');
                if (parentLi) {
                    parentLi.classList.toggle('collapsed');
                }
            });
        });
    });

    if (tutorialList) {
        listObserver.observe(tutorialList, { childList: true, subtree: true });

        // Event delegation to catch clicks on dynamically loaded list links
        tutorialList.addEventListener('click', (e) => {
            const targetLink = e.target.closest('a');
            if (!targetLink) return;

            // Remove active class from all sidebar links, about link, and home link
            tutorialList.querySelectorAll('a').forEach(link => {
                link.classList.remove('active');
            });
            const aboutLink = document.getElementById('about-link');
            if (aboutLink) aboutLink.classList.remove('active');
            const homeLink = document.getElementById('home-link');
            if (homeLink) homeLink.classList.remove('active');

            // Add active class to clicked link
            targetLink.classList.add('active');

            // Trigger entry animation for content pane
            if (contentDisplay) {
                contentDisplay.classList.remove('content-loaded-animation');
                void contentDisplay.offsetWidth; // Force reflow
                contentDisplay.classList.add('content-loaded-animation');
            }

            // Close mobile sidebar if open
            document.body.classList.remove('sidebar-open');
        });
    }

    // ----------------------------------------------------
    // 5. Dynamic About Page Fetching (CORS & file:// safe)
    // ----------------------------------------------------
    const aboutLink = document.getElementById('about-link');
    if (aboutLink) {
        aboutLink.addEventListener('click', async (e) => {
            e.preventDefault();
            
            // Clear active state of links
            if (tutorialList) {
                tutorialList.querySelectorAll('a').forEach(link => {
                    link.classList.remove('active');
                });
            }
            aboutLink.classList.add('active');
            const homeLink = document.getElementById('home-link');
            if (homeLink) homeLink.classList.remove('active');
            
            // Determine aboutUrl: use local relative path or fallback to GitHub raw on file:// protocol
            let aboutUrl = 'about.html';
            if (window.location.protocol === 'file:') {
                const username = typeof GITHUB_USERNAME !== 'undefined' ? GITHUB_USERNAME : 'OpenANR';
                const repo = typeof GITHUB_REPO !== 'undefined' ? GITHUB_REPO : 'Full-Guide-Tutorial';
                aboutUrl = `https://raw.githubusercontent.com/${username}/${repo}/main/about.html`;
            }
            
            // Fetch and render the HTML from about.html
            if (contentDisplay) {
                contentDisplay.innerHTML = `<i>Memuat halaman About...</i>`;
                try {
                    const response = await fetch(aboutUrl);
                    if (!response.ok) throw new Error('Gagal mengambil file about.html');
                    const htmlText = await response.text();
                    
                    // Parse HTML to extract only the .about-section block (ignoring standalone head/body tags)
                    const parser = new DOMParser();
                    const doc = parser.parseFromString(htmlText, 'text/html');
                    const aboutContent = doc.querySelector('.about-section');
                    
                    if (aboutContent) {
                        contentDisplay.innerHTML = aboutContent.outerHTML;
                    } else {
                        contentDisplay.innerHTML = htmlText; // Fallback to raw text if parsing fails
                    }
                } catch (error) {
                    contentDisplay.innerHTML = `
                        <div class="about-section">
                            <h1>Error</h1>
                            <p>Gagal memuat halaman About.</p>
                            <p style="font-size: 0.9rem; color: var(--text-muted);">
                                Jika Anda membukanya secara lokal (menggunakan protokol <code>file://</code>), pastikan Anda telah melakukan <code>git push</code> versi terbaru file <code>about.html</code> Anda ke GitHub.
                            </p>
                        </div>
                    `;
                    console.error("About page fetch error:", error);
                }
                
                contentDisplay.classList.remove('content-loaded-animation');
                void contentDisplay.offsetWidth; // Force reflow
                contentDisplay.classList.add('content-loaded-animation');
            }
            
            // Close mobile sidebar if open
            document.body.classList.remove('sidebar-open');
        });
    }

    // ----------------------------------------------------
    // 5a. Home Page Link Event Listener
    // ----------------------------------------------------
    const homeLink = document.getElementById('home-link');
    if (homeLink) {
        homeLink.addEventListener('click', (e) => {
            e.preventDefault();
            
            // Clear active state of tutorial links and about link
            if (tutorialList) {
                tutorialList.querySelectorAll('a').forEach(link => {
                    link.classList.remove('active');
                });
            }
            const aboutLink = document.getElementById('about-link');
            if (aboutLink) aboutLink.classList.remove('active');
            
            homeLink.classList.add('active');
            
            // Reset main content to Welcome message
            if (contentDisplay) {
                contentDisplay.innerHTML = `
                    <h1>SELAMAT DATANG DI LIBRARY TUTORIAL</h1>
                    <p>Di website ini saya pribadi menyediakan berbagai macam-macam tutorial yang membahas mulai dari sistem operasi, pemrograman, troubleshooting, dan lain-lain.</p>
                `;
                
                contentDisplay.classList.remove('content-loaded-animation');
                void contentDisplay.offsetWidth; // Force reflow
                contentDisplay.classList.add('content-loaded-animation');
            }
            
            // Close mobile sidebar if open
            document.body.classList.remove('sidebar-open');
        });
    }

    // ----------------------------------------------------
    // 6. Live Search Filter Logic
    // ----------------------------------------------------
    const searchInput = document.getElementById('docs-search');
    if (searchInput && tutorialList) {
        searchInput.addEventListener('input', (e) => {
            const query = e.target.value.toLowerCase().trim();
            const links = tutorialList.querySelectorAll('a');
            const folders = tutorialList.querySelectorAll('li');
            
            if (query === '') {
                // Reset all visibility
                links.forEach(link => {
                    link.closest('li').style.display = '';
                });
                folders.forEach(li => {
                    li.style.display = '';
                });
                return;
            }
            
            // Filter nested document links
            links.forEach(link => {
                const text = link.textContent.toLowerCase();
                const parentLi = link.closest('li');
                if (text.includes(query)) {
                    parentLi.style.display = '';
                    // Expand and show all parent directory containers (LIs)
                    let ancestor = parentLi.parentElement.closest('li');
                    while (ancestor) {
                        ancestor.style.display = '';
                        ancestor.classList.remove('collapsed');
                        ancestor = ancestor.parentElement.closest('li');
                    }
                } else {
                    parentLi.style.display = 'none';
                }
            });
            
            // Hide folders/categories that contain zero matching search result links
            const categoryLIs = tutorialList.querySelectorAll('li');
            categoryLIs.forEach(li => {
                const hasNestedUl = li.querySelector('ul');
                if (hasNestedUl) {
                    const visibleLinks = li.querySelectorAll('ul a:not([style*="display: none"])');
                    if (visibleLinks.length === 0) {
                        li.style.display = 'none';
                    } else {
                        li.style.display = '';
                    }
                }
            });
        });
    }

    // ----------------------------------------------------
    // 7. Mobile Search Layout Toggle
    // ----------------------------------------------------
    const mobileSearchBtn = document.getElementById('mobile-search-btn');
    const searchCloseBtn = document.getElementById('search-close-btn');
    const header = document.querySelector('.header');
    
    if (mobileSearchBtn && header) {
        mobileSearchBtn.addEventListener('click', () => {
            header.classList.add('search-active');
            if (searchInput) {
                searchInput.focus();
            }
        });
    }

    if (searchCloseBtn && header) {
        searchCloseBtn.addEventListener('click', () => {
            header.classList.remove('search-active');
            if (searchInput) {
                searchInput.value = '';
                // Reset sidebar filters
                searchInput.dispatchEvent(new Event('input'));
            }
        });
    }

    // ----------------------------------------------------
    // 8. Mobile Sidebar Drawer Toggle
    // ----------------------------------------------------
    const mobileToggle = document.getElementById('mobile-toggle');
    const overlay = document.getElementById('sidebar-overlay');

    if (mobileToggle) {
        mobileToggle.addEventListener('click', () => {
            document.body.classList.toggle('sidebar-open');
        });
    }

    if (overlay) {
        overlay.addEventListener('click', () => {
            document.body.classList.remove('sidebar-open');
        });
    }
});
